version: '3.7'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    expose:
      - "9000"
    volumes:
      - ./src:/var/www/html
      - ./host-vol-share/:/v-share/
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/:/var/www/html
    expose:
      - "80"
    ports:
      - 8080:80
    restart: always
    depends_on:
      - php
